[package]
name = "embree_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
viuer = "0.5"
image = "0.23"

[build-dependencies]
bindgen = "0.59"
